# Eager Execution

In [44]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

## Tensors
Basic tensor operations

In [18]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square([5, 6]))
print(tf.reduce_sum([[1,2, 3], [4, 5, 6]], axis=1))
print(tf.reduce_sum([[1,2, 3], [4, 5, 6]], axis=0))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)
tf.Tensor([ 6 15], shape=(2,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [42]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)
print(x)

(1, 2)
<dtype: 'int32'>
tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


Tensors are immutable


<tf.Tensor: id=163647, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [47]:
# Convert Numpy arrays to tensor
x = np.array([1,2])
tf.convert_to_tensor(x)

# TensorFlow operation on numpy array returns tensor
x = np.ones([3, 3])

tensor = tf.multiply(x, 10)
print(tensor)

tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]], shape=(3, 3), dtype=float64)


In [56]:
# Numpy operation on tensor returns numpy array
np.reshape(tensor, newshape=(-1,1))

array([[10.],
       [10.],
       [10.],
       [10.],
       [10.],
       [10.],
       [10.],
       [10.],
       [10.]])

## GPU Acceleration

In [60]:
x = tf.random_uniform([3, 3])

print("Is GPU available:")
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:")
print(tf.test.is_gpu_available('GPU:0'))

Is GPU available:
True
Is the Tensor on GPU #0:
True


In [68]:
def time_matmul(x):
  %timeit tf.matmul(x, x)

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# Force execution on GPU #0 if available
if tf.test.is_gpu_available():
    print("On GPU:")
    with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
        x = tf.random_uniform([1000, 1000])
        assert x.device.endswith("GPU:0")
        time_matmul(x)

On CPU:
12.7 ms ± 97.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
On GPU:
664 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Datasets

In [91]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3])

for i in ds_tensors:
    print(i)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [92]:
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
Line 2
Line 3""")
    
ds_file = tf.data.TextLineDataset(filename)

for i in ds_file:
    print(i)

tf.Tensor(b'Line 1', shape=(), dtype=string)
tf.Tensor(b'Line 2', shape=(), dtype=string)
tf.Tensor(b'Line 3', shape=(), dtype=string)


Iteration only works in eager execution mode